spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  compression:
    enabled: true

logging:
  level:
    dev.nemuki.cypherbookapi: DEBUG